export const TOGGLE_FLIPPED_CARD = 'CARD/TOGGLE_FLIPPED_CARD';
export const CHANGE_CARD_TYPE = 'CARD/CHANGE_CARD_TYPE';
export const UPDATE_CARD_TYPE = 'CARD/UPDATE_CARD_TYPE';
export const CHANGE_CARD_NUMBER = 'CARD/CHANGE_CARD_NUMBER';
export const UPDATE_CARD_NUMBER = 'CARD/UPDATE_CARD_NUMBER';
export const CHANGE_CVV = 'CARD/CHANGE_CVV';
export const SET_FOCUS_ELEMENT_PARAMETERS = 'CARD/SET_FOCUS_ELEMENT_PARAMETERS';
export const CLEAR_FOCUS_ELEMENT_PARAMETERS = 'CARD/CLEAR_FOCUS_ELEMENT_PARAMETERS';
export const CHANGE_CARD_HOLDER = 'CARD/CHANGE_CARD_HOLDER';
export const UPDATE_CARD_HOLDER = 'CARD/UPDATE_CARD_HOLDER';
export const CHANGE_CARD_HOLDER_SHOWING_PARAMETER = 'CARD/CHANGE_CARD_HOLDER_SHOWING_PARAMETER';
export const CHANGE_MONTH = 'CARD/CHANGE_MONTH';
export const UPDATE_MONTH = 'CARD/UPDATE_MONTH';
export const CHANGE_YEAR = 'CARD/CHANGE_YEAR';
export const UPDATE_YEAR = 'CARD/UPDATE_YEAR';

